apiVersion: v1
kind: Service
metadata:
  name: opentsdb
  labels:
    app: opentsdb
spec:
  type: NodePort
  ports:
  - port: 4242
    protocol: TCP
    name: http
  selector:
    app: opentsdb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: opentsdb-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opentsdb
    spec:
      containers:
      - name: opentsdb
        image: 10.98.74.120:5000/daf-opentsdb:1.0.0
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 4242
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /etc/opentsdb
          subPath: opentsdb/conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /tmp/opentsdb
          subPath: opentsdb/tmp
          readOnly: false
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hbaseconf
          mountPath: /etc/hbase/conf
          readOnly: true
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hbaseconf
        hostPath:
          path: /etc/hbase/conf
