apiVersion: v1
kind: Service
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  ports:
  - port: 9090 

  selector:
    app: nifi 
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nifi-deployment
spec:
  replicas: 3
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: nifi
    spec:
      hostNetwork: true
      containers:
      - name: nifi
        image: 10.103.136.239:5000/daf-nifi:1.0.0
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 9090
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /nificonf
          subPath: nifi/conf
          readOnly: false
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
      securityContext:
        supplementalGroups: [1330600009]
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf
