# TODO we need to put somewhere a script for adding the rootCA as a secret: kubectl create secret generic daf-root-ca --from-file= 
apiVersion: v1
kind: Service
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  ports:
  - port: 9090 
  selector:
    app: nifi 
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nifi-deployment
spec:
  replicas: 3
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: nifi
    spec:
      hostNetwork: true
      containers:
      - name: nifi
        image: 10.98.74.120:5000/daf-nifi:1.0.0
        env:
          - name: REQUESTS_CA_BUNDLE
            value: "/etc/ssl/certs/daf-root-ca.pem"
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 9090
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /nificonf
          subPath: nifi/conf
          readOnly: false
        - name: glusterfsvol
          mountPath: /nifiscripts
          subPath: nifi/scripts
          readOnly: false
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
        - name: home
          mountPath: /home
          readOnly: false
        - name: daf-root-ca
          mountPath: /etc/ssl/certs
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf
      - name: home
        hostPath:
          path: /home
      - name: daf-root-ca
        secret:
          secretName: daf-root-ca
          
