apiVersion: v1
kind: Service
metadata:
  name: livy
  labels:
    app: livy
spec:
  ports:
  - port: 8998

  selector:
    app: livy
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: livy-deployment
spec:
  replicas: 3
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: livy
    spec:
      hostNetwork: true
      containers:
      - name: livy
        image: 10.98.74.120:5000/daf-livy:1.0.0
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 8998
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /livy/conf
          subPath: livy/conf
          readOnly: true
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
      imagePullSecrets:
      - name: regsecret
      securityContext:
        supplementalGroups: [1330600009]
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf